# Generated by Django 3.2.3 on 2021-06-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='user',
            field=models.CharField(default=2, max_length=255, verbose_name='Имя пользователя'),
            preserve_default=False,
        ),
    ]
